from example_for_tests.mediumscattering import test_mediumscattering
from example_for_tests.mri import test_mri
from example_for_tests.xray_phase_contrast import test_xray_phase_contrast
from example_for_tests.volterra_irgnm_cg_impulsive_noise import test_volterra_irgnm_cg_impulsive_noise
from example_for_tests.potential import test_potential
from example_for_tests.volterra_irgnm_cg import test_volterra_irgnm_cg
from example_for_tests.volterra_landweber import test_volterra_landweber
from example_for_tests.volterra_tikhonov_cg import test_volterra_tikhonov_cg