import logging
#from multiprocessing.spawn import get_command_line

import numpy as np
from numpy.linalg import norm
from math import isfinite
from scipy.io import loadmat, savemat
from scipy.optimize import lsq_linear
from copy import deepcopy
import regpy.stoprules as rules
from regpy.vecsps import UniformGridFcts, DirectSum
from regpy.vecsps.tensor_bases import chebyshev_basis, legendre_basis
from regpy.hilbert import L2, Sobolev, HmDomain
import regpy.hilbert as hilbert
from regpy.operators import Identity
from regpy.operators import CoordinateProjection, Zero, InnerShift, OuterShift
from regpy.operators import DirectSum as opDirectSum
from regpy.operators.PINEM import PINEM_g_to_data, complex_PINEM_g_to_data
from regpy.solvers import HilbertSpaceSetting
from regpy.solvers.nonlinear.irgnm import IrgnmCG
from regpy.solvers.nonlinear.newton import NewtonCG
from regpy.util.imshow_fig import ImShowFig, complex_to_rgb, complex_to_rgb_log 
import sys
sys.path.append('./PINEM')
from PINEM_plots import plot_exact_solution_data,plot_reco, plot_stats, init_plot_stats
from PINEM_setup import setup_simulated_g, ForgetSecond
from PINEM_extensions import harmonic_extension, extension_along_lines
import matplotlib.pyplot as plt

def main():
    ################################ set parameters 

    # intermediate results will be written to file names starting with output_filename
    output_filename = r'./test'
    logging.basicConfig(
       level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)-20s :: %(message)s",
        handlers=[
            logging.FileHandler(output_filename+'.log',mode='w'),
            logging.StreamHandler()
        ]
    )
    # If None, the initial guess is either zero (for synthetic g) or constructed from initial 
    # partial knowledge of |g| and phase(g)
    # Otherwise, if it is an output of a previous inversion method, this reconstruction is used as initial guess
    init_guess_filename = None #r'./adaptive_IRGNM/test46.mat'
    # Name of file containing experimental data. 
    # If this is not None, data (i.e. the right hand side of the operator equation) will be loaded from this file rather 
    # then generated by simulation, i.e. application of the forward operator to g and adding noise.
    experimental_data_filename = None
    #experimental_data_filename = r'./data/data_N30_1e10.mat'                      
    # If true, the unknown g will be parameterized as a usual complex-valued grid function, 
    # otherwise by its modulus and phase: (ex_amp,ex_phase)|-> ex_amp * exp(1j*ex_phase) = g
    g_is_complex = False
    # use additional measurement of |g|^2 from EELS as part of the forward operator
    using_gabs_measurement = False
    # If true, abs(g) is assumed to be known outside of the nanotip.
    # If g_is_complex==False, this is imposed as contraint, otherwise it is used as initial guess. 
    abs_g_is_partly_known = True
    assert g_is_complex or (not abs_g_is_partly_known or not using_gabs_measurement)
    # If using_polynomial_basis_for_phase==True, the phase will be parameterized by 
    # a tensor-product polynomial basis of degrees pol_degrees in x and y directions. 
    # Starting with small polynomial degrees helps to avoid getting trapped in local minimima.
    # Only relevant if g_is_complex==False.
    using_polynomial_basis_for_phase = False
    pol_degrees = (20,7)
    # total number of counts for gain and loss data
    total_nr_counts = 2e9
    # total number of counts for EELS data
    total_nr_counts_gabs = 1e12
    # turn off/on all plots
    do_plottings = True
    # use log(|g|) instead of |g| for darkness in phase plots of g and g_rec. Makes phase visible everywhere
    plot_log_g = True
    # number of modes used for evaluations of forward operator and generation of simulated data
    N_data = 30
    # values of N used for evaluation of the derivative of the forward operator
    # This value should gradually be increased to save computation time. 
    N_deriv = [4,8,16,30]
    # solver type: If True, NewtonCG is used, otherwise IrgnmCG
    use_NewtonCG = True
    if g_is_complex:
        sobolev_index = 2
        IRGNM_regpar = 1e-4; IRGNM_regpar_step = 0.8
    else:
        sobolev_index_phase = 2; sobolev_index_ampl = 2
        IRGNM_regpar = 1e-15
        IRGNM_regpar_step = 2/3
        IRGNM_cgstop = 1000
        NewtonCG_rho = 0.95
        NewtonCG_cgmaxit = 50
    # If the norm of the residual (=data-predicted data) decreases by less than minimal_residual_reduction, 
    # then N is increased to the next value in N_deriv
    minimal_residual_reduction = 0.98 # NewtonCG_rho**0.5
    # Maximum number of Newton iterations for each value of N
    max_Newton_its = 20

    op, grid, exact_solution, g_map, mask_a, mask_p, opdata \
        = setup_simulated_g(g_is_complex=g_is_complex, 
                            using_gabs_measurement = using_gabs_measurement,
                            #list_of_filters= [ [1,3,5,7],[-1,-3,-5,-7]],
                            N=N_data,
                            parallel=True
                            )

    # uncomment this if amplitude of g assumed to be known everywhere
    # mask_a = np.full(mask_a.shape,False,dtype=bool)
    
    ################################################   initialize forward operator
    if g_is_complex:
        # h_domain = Sobolev(grid.complex_space(), index=sobolev_index)
        h_domain = HmDomain(grid.complex_space(),mask_p, index = sobolev_index)
        g0 = harmonic_extension(1-mask_p,g_map)
        proj = CoordinateProjection(grid.complex_space(),mask_p)
        projection = InnerShift(proj,g0)
        extension = OuterShift(proj.adjoint,g0)
    else:
        if abs_g_is_partly_known:
            if mask_a.any():
                prior_ampl = harmonic_extension(~mask_a,np.log(np.abs(g_map)),damping =0)
                #mask = mask_a_org.copy()
                #mask[-1,:]=1; mask[-1,:]=1; mask[:,-1] = 1
                # prior_ampl = extension_along_lines(np.log(np.abs(g_map)),mask)
                ampl_proj = CoordinateProjection(grid, mask_a)
                ampl_domain = HmDomain(grid.real_space(),mask_a, index = sobolev_index_ampl)
            else: # amplitude is known everywhere
                prior_ampl = np.log(np.abs(g_map))
                ampl_proj = Zero(grid)
                ampl_domain = L2(grid) # irrelevant, only needed formally
        else:
            prior_ampl = harmonic_extension(~mask_p,np.log(np.abs(g_map)),damping =0)
            ampl_proj = CoordinateProjection(grid, mask_p)
            ampl_domain = HmDomain(grid.real_space(), np.ones(grid.shape,dtype=int), index = sobolev_index_ampl)
        ampl_projection = InnerShift(ampl_proj,prior_ampl)
        ampl_extension = OuterShift(ampl_proj.adjoint,prior_ampl)

        if using_polynomial_basis_for_phase:
            coeff_grid = UniformGridFcts(np.arange(pol_degrees[0]),np.arange(pol_degrees[1]))
            phase_domain = L2(coeff_grid)         
            phase_extension =  legendre_basis(coeff_grid,grid)
            phase_projection = phase_extension.adjoint
        else:
            # outer boundary values of phase must also be fixed for use of Sobolev norm
            #prior_phase = harmonic_extension(~mask_p,np.unwrap(np.angle(g_map.T)).T,damping =0)
            prior_phase = np.unwrap(np.angle(g_map.T)).T
            phase_proj = CoordinateProjection(grid, mask_p)
            phase_projection = InnerShift(phase_proj,prior_phase)
            phase_extension = OuterShift(phase_proj.adjoint,prior_phase)
            #phase_projection = InnerShift(Identity(grid),prior_phase)
            #phase_extension = OuterShift(Identity(grid),prior_phase)
            weight = (0.02+np.exp(prior_ampl)/np.exp(np.max(prior_ampl)))
            #weight = np.ones_like(g_map.real)*g_map.shape[0]**2
            phase_domain = HmDomain(grid.real_space(),mask_p, index = sobolev_index_phase, weight = weight)

        h_domain = ampl_domain + phase_domain
        projection =  opDirectSum(ampl_projection, phase_projection)
        extension = opDirectSum(ampl_extension,phase_extension)

    # as extension is also needed for plotting, a copy is required to avoid errors 
    # on the use of revoked copies 
    extension2 = deepcopy(extension)
    op_ext = op * extension2

    ############################### compute synthetic data or load experimental data from file
    flat_codomain = DirectSum(*op.codomain.summands, flatten=True)
    if experimental_data_filename:
        print(experimental_data_filename)
        dat = loadmat(experimental_data_filename)
        data = dat['data']
        data = np.reshape(data,(data.shape[1],))
        if using_gabs_measurement:
            raise NotImplemented
        else:
            if isfinite(total_nr_counts):
                scal = np.sum(data)/total_nr_counts
            else:
                scal = 1
        data_comp = op.codomain.split(data)
    else:
        if using_gabs_measurement:
            exact_data = op(exact_solution)
            #exact_data = op_ext(projection(exact_solution))
            exact_data_comp = op.codomain.split(exact_data)
            if isfinite(total_nr_counts_gabs):
                scal_gabs = np.sum(exact_data_comp[0])/total_nr_counts_gabs
                noisy_data0 = scal_gabs * np.random.poisson(exact_data_comp[0]/scal_gabs)
            else:
                noisy_data0 = exact_data_comp[0] 
                scal_gabs = 1
            if isfinite(total_nr_counts):
                scal = np.sum(exact_data_comp[1])/total_nr_counts
                noisy_data1 = scal*np.random.poisson(exact_data_comp[1]/scal)
            else:
                noisy_data1 = exact_data_comp[1]
                scal = 1
            data = op.codomain.join(noisy_data0, noisy_data1)
        else:
            exact_data = op(exact_solution)
            if isfinite(total_nr_counts):
                scal = np.sum(exact_data)/total_nr_counts
                data = scal*np.random.poisson(exact_data/scal)
            else:
                data = exact_data
                scal =1
            data_comp = op.codomain.split(data)
        savemat(output_filename+'_data.mat',{'data':data})


    ################################## define Hilbert space setting
    if using_gabs_measurement:
        h_codomain0 = L2(grid, weights = 1/(scal_gabs**2 + scal_gabs*data_comp[0]))
        data_comp = flat_codomain.split(data)
        h_codomain1 = L2(grid, weights=1/(scal**2 + scal*data_comp[1]))
        for j in range(2, len(flat_codomain)):
            h_codomain1 = h_codomain1 + L2(grid, weights=1/(scal**2 +scal*data_comp[j]))
        h_codomain = hilbert.DirectSum(h_codomain0, h_codomain1)
    else:
        # define codomain Gram matrix based on observed data to approximate log-likelihood
        h_codomain = L2(grid, weights=1/(scal**2+scal*data_comp[0])) 
        for j in range(1, len(data_comp)):
            h_codomain = h_codomain + L2(grid, weights=1/(scal**2 + scal*data_comp[j]))
    #setting = HilbertSpaceSetting(op=op_ext, h_domain=h_domain, h_codomain=h_codomain)

    ##################### define initial guess
    if init_guess_filename:
        assert not using_polynomial_basis_for_phase
        mat = loadmat(init_guess_filename)
        init_ampl = mat['reco_amp']
        init_phase = mat['reco_phase']
        if g_is_complex:
            init_vec = init_ampl * np.exp(1j * init_phase)
        else:
            init_vec = op.domain.join(np.log(init_ampl), init_phase)
    else:
        angle = np.deg2rad(10)
        X, Y = np.meshgrid(np.linspace(0, 1, np.size(mask_a, 1)), np.linspace(0, 1, np.size(mask_a, 0)))
        init_phase = -1 * (np.sin(angle)*X + np.cos(angle)*Y) * 2*np.pi * 3 + 2.5
        if g_is_complex:
            if abs_g_is_partly_known:
                g0 = abs(g_map) * np.exp(1j*init_phase)
                init_vec = harmonic_extension(~mask_a,(1-mask_a) * g0)
            else:
                init_vec = grid.complex_space().ones() * mask_a
        else:
            if using_polynomial_basis_for_phase:
                T = phase_extension.as_linear_operator() # Legendre basis
                init_phase_coeff_flat = lsq_linear(T,grid.flatten(init_phase)).x
                init_phase_coeff = phase_extension.domain.fromflat(init_phase_coeff_flat)
                init_vec_proj = op_ext.domain.join(ampl_projection(prior_ampl),init_phase_coeff)
            else:
                init_vec = op.domain.join(prior_ampl,init_phase)
    if not using_polynomial_basis_for_phase:
        init_vec_proj = projection(init_vec)

    ############################### initialize stopping rule
   
    if using_gabs_measurement:
        data_comp = flat_codomain.split(data)
        nr_data = len(data_comp)
        sqrtdata = flat_codomain.join(*[np.sqrt(scal_gabs*data_comp[0]),
            *[np.sqrt(scal*data_comp[k]) for k in range(1,nr_data)]])
    else:
        sqrtdata = np.sqrt(scal*data) 

    discrepancy_rule = rules.Discrepancy(
            h_codomain.norm,
            data,
            noiselevel= h_codomain.norm(sqrtdata),
            tau=1
        )
    stoprule = (discrepancy_rule + rules.CountIterations(max_iterations=max_Newton_its,while_type=True))
      
    ############################## routines for reconstruction error evaluation  
    def reconstruction_error(_exact, _reconstruction):
        def fnorm(arr):
            return norm(arr[:])

        nonlocal g_is_complex
        if g_is_complex:
            reco_error1 = fnorm((np.abs(_reconstruction)-np.abs(_exact)))/fnorm(_exact)
            ex_phase = np.unwrap(np.angle(_exact.T)).T
            reco_phase = np.unwrap(np.angle(_reconstruction.T)).T
            reco_error2 = fnorm(np.exp(1j*reco_phase)-np.exp(1j*ex_phase))/np.sqrt(np.prod(_exact.shape))
            reco_error3 = fnorm(_reconstruction-_exact)/fnorm(_exact)
        else:
            log_ex_amp, ex_phase = op.domain.split(_exact)
            reco_amp, reco_phase = op.domain.split(_reconstruction)
            ex_amp = np.exp(log_ex_amp)
            reco_error1 = fnorm(reco_amp-ex_amp)/fnorm(ex_amp)
            reco_error2 = fnorm(np.exp(1j*reco_phase)-np.exp(1j*ex_phase))/np.sqrt(np.prod(ex_phase.shape))
            # fnorm((reco_phase-ex_phase))/fnorm(ex_phase)
            reco_error3 = fnorm(reco_amp*np.exp(1j*reco_phase) -ex_amp*np.exp(1j*ex_phase))/fnorm(ex_amp)
        return reco_error1, reco_error2, reco_error3

    def plot_write_safe(reco,reco_data,fig1,fig2,axs3, newton_step,
        do_plottings=do_plottings, stats =None,output_filename = None,N=None
        ):

        ereco = extension(reco)

        # fix unidentified constant global phase 
        if g_is_complex:
            ex_phase = np.unwrap(np.angle(exact_solution.T)).T
            reco_phase = np.unwrap(np.angle(ereco.T)).T
            reco_amp = np.abs(ereco)
        else:
            _, ex_phase = op.domain.split(exact_solution)
            reco_amp, reco_phase = op.domain.split(ereco)
            reco_amp = np.exp(reco_amp)
        phase_correction = np.median(ex_phase[~mask_a])-np.median(reco_phase[~mask_a]) 
        reco_phase += phase_correction
        if g_is_complex:
            ereco = reco_amp * np.exp(1j*reco_phase)
        else:
            ereco = op.domain.join(reco_amp,reco_phase)
            
        reco_error1, reco_error2, reco_error3 = reconstruction_error(exact_solution, ereco)
        stats['Newton step'].append(newton_step)
        stats['ampl_err'].append(reco_error1)
        stats['phase_err'].append(reco_error2)
        stats['complex_err'].append(reco_error3)
        stats['residuals'].append(setting.h_codomain.norm(reco_data-data))
        stats['N'].append(N)
        if hasattr(solver, "nr_inner_its") and callable(solver.nr_inner_its):
            stats['nr_inner_steps'].append(solver.nr_inner_its())

        if output_filename:
            savemat(output_filename+'{}.mat'.format(newton_step),
            {'reco_amp':reco_amp, 'reco_phase': reco_phase, **stats}
            )
        if newton_step>0:
            residual_reduction = stats['residuals'][-1]/stats['residuals'][-2]
            logging.info('it.{}, N={}, modulus: {:1.4f}, phase: {:1.4f}, norm: {:1.4f}, resid.reduct: {:1.4f}'.format(
                newton_step, N,reco_error1, reco_error2, reco_error3,residual_reduction))
        else:
            residual_reduction = 1
            logging.info('it.{}, N={}, modulus: {:1.4f}, phase: {:1.4f}, norm: {:1.4f}'.format(
                newton_step, N,reco_error1, reco_error2, reco_error3))

        reco_data_comp = flat_codomain.split(reco_data)
        ex_data_comp = flat_codomain.split(data)

        if do_plottings:
            plot_reco(fig1,fig2,reco_amp,reco_phase,reco_data_comp,g_map,ex_data_comp,newton_step,mask_a = mask_a)
            plot_stats(axs3,stats,plot_inner_its = hasattr(solver, "nr_inner_its") and callable(solver.nr_inner_its))

        return residual_reduction

    ########################################## perform inversion

    setting = HilbertSpaceSetting(op=op_ext, h_domain=h_domain, h_codomain=h_codomain)
    if N_deriv:
        N_current = N_deriv[0]
        op_simple = PINEM_g_to_data(*opdata, N=N_current) * deepcopy(extension)
    else:
        N_current = N_data
        op_simple = None
    if use_NewtonCG:
       solver = NewtonCG(
            setting, data, init=init_vec_proj,
            cgmaxit=NewtonCG_cgmaxit, rho=NewtonCG_rho,
            simplified_op = op_simple
         )
    else:
        solver = IrgnmCG(
            setting, data, init=init_vec_proj,
            regpar=IRGNM_regpar, regpar_step=IRGNM_regpar_step,
            cgstop=IRGNM_cgstop,
            inner_it_logging_level=logging.INFO,
            simplified_op = op_simple
            )

    fig1,fig2 = plot_exact_solution_data(g_map,data_comp,
                            using_gabs_measurement = using_gabs_measurement,plot_log_g = plot_log_g)       
    fig3, axs3 = init_plot_stats()
    
    stats = {'ampl_err': [], 'phase_err': [], 'complex_err': [], 'residuals': [], 'nr_inner_steps': [], \
        'N': [], 'Newton step' : []}
    newton_step=0
    plot_write_safe(solver.x,solver.y,fig1,fig2,axs3,newton_step,
        do_plottings=do_plottings,stats=stats,output_filename= output_filename,N=N_current)
      
    for newton_step, [reco, reco_data] in enumerate(solver.while_(stoprule),1):
        residual_reduction = plot_write_safe(solver.x,solver.y,fig1,fig2,axs3,newton_step,
            do_plottings=do_plottings,stats=stats,output_filename= output_filename,N=N_current)
        if residual_reduction > minimal_residual_reduction:
            break

    for N_current in N_deriv[1:]:
        residual_last_N= stats['residuals'][-1]
        op_simple = PINEM_g_to_data(*opdata, N=N_current) * deepcopy(extension)
        if use_NewtonCG:
            solver = NewtonCG(
                setting, data, init=stoprule.x,
                cgmaxit=NewtonCG_cgmaxit, rho=NewtonCG_rho,
                simplified_op = op_simple
            )
        else:
            solver = IrgnmCG(
                setting, data, init=stoprule.x,
                regpar=IRGNM_regpar*IRGNM_regpar_step**(newton_step-1), 
                regpar_step=IRGNM_regpar_step,
                cgstop=IRGNM_cgstop,
                inner_it_logging_level=logging.INFO,
                simplified_op = op_simple
            )

        stoprule = (discrepancy_rule + rules.CountIterations(max_iterations=max_Newton_its,while_type=True))
        plot_write_safe(solver.x,solver.y,fig1,fig2,axs3,newton_step,
           do_plottings=True,stats=stats,output_filename= output_filename,N=N_current)

        for newton_step, [reco, reco_data] in enumerate(solver.while_(stoprule),newton_step+1):
            residual_reduction = plot_write_safe(solver.x,solver.y,fig1,fig2,axs3,newton_step,
                do_plottings=True,stats=stats,output_filename= output_filename,N=N_current)
            if residual_reduction > minimal_residual_reduction and stats['residuals'][-1] < residual_last_N*NewtonCG_rho:
                break
    if do_plottings:
        plt.show(block=True)
if __name__ == '__main__':
    main()
