# Parameter structure for the problem
p:
  # Number of incident directions
  N_INC: 32
  
  # Number of measurement directions                   
  N_MEAS: 256
  
  # The shape of the grid in the domain space                  
  GRID_SHAPE: [100,100]  #dx = 0.4/kappa, N = 4/dx
  
  # Inhomogeneity is supported in a circle centered at origin of a given radius
  SUPPORT_RADIUS: 1
  
  WAVE_NUMBER: 10
  
  # Available potentials: bell, peaks
  POTENTIAL: bell
  
  # Geometry setup of incident and measurement directions
  GEOMETRY_SETUP: ONE_TO_MANY
  
  # Number of iterations for computation of the inverse NFFT
  # and residue tolerance
  INFFT_NUM_ITER: 30
  INFFT_THRESHOLD: 1e-3  
  
  NOISE_LVL: 0.00

# Parameters of the reconstruction method  
m:
  RADIUS: [0.3,0.35,0.4,0.45,0.5,0.5,0.5,0.5] 
  #RADIUS: [0.2,0.25,0.25,0.25,0.3]
  MAXITER: 20